# 基本设置
port: 7890 # HTTP代理端口
socks-port: 7891 # SOCKS代理端口
#redir-port: 7892 # 透明代理端口，用于 Linux 和 MacOS
mixed-port: 7893 # HTTP(S) 和 SOCKS 代理混合端口
#tproxy-port: 7894
allow-lan: false # 允许局域网连接
bind-address: "*" # 绑定地址，* 表示所有地址
mode: rule # 代理模式，rule表示规则模式
log-level: info # 日志级别
ipv6: true
#  控制面板
# external-controller: 0.0.0.0:9093 # RESTful API 监听地址
# external-controller-tls: 0.0.0.0:9443 # RESTful API HTTPS 监听地址，需要配置 tls 部分配置文件
# secret: "123456"
# external-ui: ui
# external-ui-name: zashboard
# external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

unified-delay: true # 统一延迟
tcp-concurrent: true # TCP 并发

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
find-process-mode: strict
global-client-fingerprint: chrome

#  TCP keep alive interval
#  这个选项大概用不到
# disable-keep-alive: false #目前在android端强制为true
# keep-alive-idle: 600
# keep-alive-interval: 15

profile:
  store-selected: true # 存储 select 选择记录
  store-fake-ip: true # 持久化 fake-ip

# 入站  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# 嗅探
sniffer:
  sniff:
    TLS:
      ports: [443, 8443]
      override-destination: true
    HTTP:
      ports: [80, 8080, 8880]
      override-destination: false
    QUIC:
      ports: [443, 8443]
      override-destination: true
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"

dns:
  enable: true
  ipv6: true
  listen: '0.0.0.0:53'
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver: 
    - "tls://223.5.5.5:853" # 阿里 DoT
    - "https://1.12.12.12/dns-query" # 腾讯 DoH
  nameserver:
    - https://doh.apad.pro/dns-query
#    - https://doh.18bit.cn/dns-query
    - https://dns.twnic.tw/dns-query
    - tls://[2001:4860:4860::64]:853
    - 4.2.2.1
    - 4.2.2.2
    - 202.181.240.44
    - 210.0.255.251
    - 101.101.101.101
    - 101.102.103.104    
#    - 2001:da8:8000:1:202:120:2:100
#    - 2001:da8:8000:1:202:120:2:101
  nameserver-policy:
    geosite:cn,private,steam:
      - tls://dns.alidns.com
      - 223.5.5.5
      - 180.184.1.1 #字节跳动 DNS
      - 180.184.2.2
      - 2001:da8:8000:1:202:120:2:100 #上交大 DNS
      - 2001:da8:8000:1:202:120:2:101
#      - 2001:da8:202:10::36 #北京邮电大学
#      - 2001:da8:202:10::37      
  direct-nameserver:
    - tls://223.5.5.5:853
    - 180.184.1.1 #字节跳动 DNS
    - 180.184.2.2
    - 2001:da8:8000:1:202:120:2:100 #上交大 DNS
    - 2001:da8:8000:1:202:120:2:101 
    - 202.96.128.86 #中国电信 DNS
    - 202.96.134.33
    - 240e:1f:1::1
    - 240e:1f:1::33
    - 210.2.4.8 #CNNIC
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - swscan.apple.com
    - mesu.apple.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'msftconnecttest.com'
    - 'msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.mcdn.bilivideo.cn'
#  fallback:
#    - https://1.1.1.1/dns-query
#    - https://dns.google/dns-query
#    - https://doh.apad.pro/dns-query
#    - https://dns.twnic.tw/dns-query
#  fallback-filter:
#    geoip: false
#    ipcidr:
#      - 0.0.0.0/8
#      - 10.0.0.0/8
#      - 100.64.0.0/10
#      - 127.0.0.0/8
#      - 169.254.0.0/16
#      - 172.16.0.0/12
#      - 192.0.0.0/24
#      - 192.0.2.0/24
#      - 192.88.99.0/24
#      - 192.168.0.0/16
#      - 198.18.0.0/15
#      - 198.51.100.0/24
#      - 203.0.113.0/24
#      - 224.0.0.0/4
#      - 240.0.0.0/4
#      - 255.255.255.255/32
#      - ::1/128
#      - fc00::/7
#      - fe80::/10
#    domain:
#      - '+.google.com'
#      - '+.facebook.com'
#      - '+.youtube.com'
#      - '+.githubusercontent.com'
#      - '+.googlevideo.com'
#      - "+.jsdelivr.net"
#      - "+.github.com"
#      - "+.githubusercontent.com"
#      - "sub.id9.cc"
#      - "sub.xeton.dev"
#      - "api.dler.io"
#      - "sub.maoxiongnet.com"

# geodata-mode: true/false
geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb"

proxy-groups:
  - name: 节点选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - 自动选择
      - 故障转移
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
  - name: 手动切换
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 自动选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    include-all: true
    exclude-filter: (?i)家宽|家庭|商宽|落地
    interval: 300
    tolerance: 20
    # lazy: false
  - name: Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies:
      - 节点选择
      - 故障转移
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: Google
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - 节点选择
      - 故障转移
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies:
      - 节点选择
      - 故障转移
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: FCM推送
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - 全球直连
      - 节点选择
  - name: 全球直连
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 节点选择
  - name: 广告拦截
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - 全球直连
  - name: 漏网之鱼
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png
    type: select
    proxies:
      - 节点选择
      - 全球直连
  - name: 故障转移
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png
    type: fallback
    # lazy: false
    proxies:
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 香港节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)港|HK|hk|Hong Kong|HongKong|hongkong
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 台湾节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 日本节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 日本负载-轮询
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    type: load-balance
    strategy: round-robin  # <-- 核心策略：轮询
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: false
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    exclude-filter: (?i)家宽|家庭|商宽|落地
  - name: 美国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 美国负载-轮询
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    type: load-balance
    strategy: round-robin  # <-- 核心策略：轮询
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: false
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    exclude-filter: (?i)家宽|家庭|商宽|落地
  - name: GLOBAL
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    type: select
    proxies:
      - 节点选择
      - 手动切换
      - 自动选择
      - Telegram
      - Google
      - YouTube
      - 游戏平台
      - 静态资源
      - FCM推送
      - 全球直连
      - 广告拦截
      - 漏网之鱼
      - 故障转移
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点

rule-providers:
  ADBlock:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://adrules.top/adrules_domainset.txt
    path: ./ADBlock.txt
  GoogleFCM:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./ruleset/FirebaseCloudMessaging.list
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list
  gfw:
    type: http
    behavior: domain
    format: text
    interval: 86400
    path: ./ruleset/gfw.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
  cmtyPROXYrules:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/cmtyPROXYrules.list
    url: https://raw.githubusercontent.com/cmyyx/backup/refs/heads/cmty-rules/cmtyPROXYrules.list
  cmtyDIRECTrules:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/cmtyDIRECTrules.list
    url: https://raw.githubusercontent.com/cmyyx/backup/refs/heads/cmty-rules/cmtyDIRECTrules.list
  AWAvenue-Ads-Rule:
    type: http
    behavior: domain
    format: yaml
    path: ./ruleset/AWAvenue-Ads-Rule-Clash.yaml
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml
    interval: 86400

rules:
  - "RULE-SET,cmtyPROXYrules,节点选择"
  - "RULE-SET,cmtyDIRECTrules,全球直连"
  - "RULE-SET,ADBlock,广告拦截"
  - "RULE-SET,AWAvenue-Ads-Rule,广告拦截"
  - "RULE-SET,GoogleFCM,全球直连"
  - "RULE-SET,gfw,节点选择"
  - "GEOSITE,YOUTUBE@CN,全球直连"
  - "GEOSITE,YOUTUBE,YouTube"
  - "GEOSITE,GOOGLE-PLAY@CN,全球直连"
  - "GEOSITE,GOOGLE,Google" 
  - "GEOSITE,CATEGORY-GAMES@CN,全球直连"
  - "GEOSITE,CATEGORY-GAMES,游戏平台"
  - "GEOSITE,CATEGORY-SCHOLAR-CN,全球直连"
  - "GEOSITE,TELEGRAM,Telegram"
  - "GEOSITE,CN,全球直连"
  - "GEOSITE,PRIVATE,全球直连"
  - "GEOIP,GOOGLE,Google,no-resolve"
  - "GEOIP,TELEGRAM,Telegram,no-resolve"
  - "GEOIP,CN,全球直连,no-resolve"
  - "GEOIP,LAN,全球直连,no-resolve"
  - "GEOIP,PRIVATE,全球直连,no-resolve"
  - "MATCH,漏网之鱼"