# 基本设置
port: 7890 # HTTP代理端口
socks-port: 7891 # SOCKS代理端口
#redir-port: 7892 # 透明代理端口，用于 Linux 和 MacOS
mixed-port: 7893 # HTTP(S) 和 SOCKS 代理混合端口
#tproxy-port: 7894
allow-lan: false # 允许局域网连接
bind-address: "*" # 绑定地址，* 表示所有地址
mode: rule # 代理模式，rule表示规则模式
log-level: info # 日志级别
ipv6: false
#  控制面板
# external-controller: 0.0.0.0:9093 # RESTful API 监听地址
# external-controller-tls: 0.0.0.0:9443 # RESTful API HTTPS 监听地址，需要配置 tls 部分配置文件
# secret: "123456"
# external-ui: ui
# external-ui-name: zashboard
# external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

unified-delay: true # 统一延迟
tcp-concurrent: true # TCP 并发

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
find-process-mode: strict
global-client-fingerprint: chrome

#  TCP keep alive interval
#  这个选项大概用不到
# disable-keep-alive: false #目前在android端强制为true
# keep-alive-idle: 600
# keep-alive-interval: 15

profile:
  store-selected: true # 存储 select 选择记录
  store-fake-ip: true # 持久化 fake-ip

# 入站  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# 嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"

dns:
  enable: true
  ipv6: false
  respect-rules: true
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  use-system-hosts: true
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - 'geosite:private'
    - 'geosite:cn'
    - 'geosite:apple-cn'
    - '*.lan'
    - localhost.ptlogin2.qq.com
  # 用于解析 nameserver，fallback 以及其他 DNS 服务器配置的，DNS 服务域名
  # 只能使用纯 IP 地址，可使用加密 DNS
#  default-nameserver:
#    - system # append DNS server from system configuration. If not found, it would print an error log and skip.
#    - 8.8.8.8           # Google DNS
#    - 1.1.1.1           # Cloudflare DNS
#    - 119.29.29.29      # 腾讯DNSPod
#    - 223.5.5.5         # 阿里DNS
#    - 223.6.6.6         # 阿里DNS
#    - 180.76.76.76      # 百度DNS
  # 专用于direct出口域名解析的 DNS 服务器，非必要配置项，如果不填则遵循nameserver-policy、nameserver和fallback的配置
#  direct-nameserver-follow-policy: false # 是否遵循nameserver-policy，默认为不遵守，仅当direct-nameserver不为空时生效
#  direct-nameserver:
#    - system
#    - https://doh.pub/dns-query
#    - https://dns.alidns.com/dns-query
#    - 114.114.114.114
#    - 223.5.5.5
#    - 119.29.29.29
  # 专用于节点域名解析的 DNS 服务器，非必要配置项，如果不填则遵循nameserver-policy、nameserver和fallback的配置
#  proxy-server-nameserver:
#    - 223.5.5.5
#    - 119.29.29.29
#    - https://dns.google/dns-query
#    - tls://one.one.one.one
  nameserver:
#    - system
    - 114.114.114.114
    - 223.5.5.5
    - 119.29.29.29
    - "https://dns.google/dns-query"
    - "https://dns.cloudflare.com/dns-query"

# geodata-mode: true/false
geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb"

proxy-groups:
  - name: 节点选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - 自动选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
  - name: 手动切换
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 自动选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    include-all: true
    exclude-filter: (?i)家宽|家庭|商宽|落地
    interval: 300
    tolerance: 20
    # lazy: false
  - name: Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: Google
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: E-Hentai
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Ehentai.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 游戏平台
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 静态资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: select
    include-all: true
    proxies:
      - 日本负载-轮询
      - 美国负载-轮询
      - 节点选择
      - 自动选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 媒体CDN
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Filter.png
    type: select
    proxies:
      - 日本负载-轮询
      - 美国负载-轮询
      - 节点选择
      - 自动选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: FCM推送
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - 全球直连
      - 节点选择
  - name: 全球直连
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 节点选择
  - name: 广告拦截
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - 全球直连
  - name: 漏网之鱼
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png
    type: select
    proxies:
      - 节点选择
      - 全球直连
  - name: 故障转移
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png
    type: fallback
    # lazy: false
    proxies:
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 香港节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)港|HK|hk|Hong Kong|HongKong|hongkong
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 台湾节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 日本节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 日本负载-轮询
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    type: load-balance
    strategy: round-robin  # <-- 核心策略：轮询
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: false
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    exclude-filter: (?i)家宽|家庭|商宽|落地
  - name: 美国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 美国负载-轮询
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    type: load-balance
    strategy: round-robin  # <-- 核心策略：轮询
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: false
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    exclude-filter: (?i)家宽|家庭|商宽|落地
  - name: GLOBAL
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    type: select
    proxies:
      - 节点选择
      - 手动切换
      - 自动选择
      - Telegram
      - Google
      - YouTube
      - E-Hentai
      - 游戏平台
      - 静态资源
      - 媒体CDN
      - FCM推送
      - 全球直连
      - 广告拦截
      - 漏网之鱼
      - 故障转移
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点

rule-providers:
  ADBlock:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://adrules.top/adrules_domainset.txt
    path: ./ADBlock.txt
  cdn_domainset:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./sukkaw_ruleset/cdn_domainset.txt
  cdn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./sukkaw_ruleset/cdn_non_ip.txt
  EHentai:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/EHentai.list
    path: ./ruleset/EHentai.list
  GoogleFCM:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./ruleset/FirebaseCloudMessaging.list
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list
  AdditionalFilter:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/AdditionalFilter.list
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalFilter.list
  gfw:
    type: http
    behavior: domain
    format: text
    interval: 86400
    path: ./ruleset/gfw.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
  ProxyGFWlist:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.yaml
    interval: 86400
  ProxyGFW:
    type: http
    behavior: classical
    url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/ProxyGFW.list
    path: ./rule-providers/ProxyGFW.list
  cmtyPROXYrules:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/cmtyPROXYrules.list
    url: https://raw.githubusercontent.com/cmyyx/backup/refs/heads/cmty-rules/cmtyPROXYrules.list
  cmtyDIRECTrules:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/cmtyDIRECTrules.list
    url: https://raw.githubusercontent.com/cmyyx/backup/refs/heads/cmty-rules/cmtyDIRECTrules.list
  cmtyPROXYmedia_cdn:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/cmtyPROXYmedia_cdn.list
    url: https://raw.githubusercontent.com/cmyyx/backup/refs/heads/cmty-rules/cmtyPROXYmedia_cdn.list
  AWAvenue-Ads-Rule:
    type: http
    behavior: domain
    format: yaml
    path: ./ruleset/AWAvenue-Ads-Rule-Clash.yaml
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml
    interval: 86400

rules:
  - "RULE-SET,cmtyPROXYmedia_cdn,媒体CDN"
  - "RULE-SET,cmtyPROXYrules,节点选择"
  - "RULE-SET,cmtyDIRECTrules,全球直连"
  - "RULE-SET,ADBlock,广告拦截"
  - "RULE-SET,AdditionalFilter,广告拦截"
  - "RULE-SET,AWAvenue-Ads-Rule,广告拦截"
  - "RULE-SET,cdn_domainset,静态资源"
  - "RULE-SET,cdn_non_ip,静态资源"
  - "RULE-SET,EHentai,E-Hentai"
  - "RULE-SET,GoogleFCM,全球直连"
  - "RULE-SET,gfw,节点选择"
  - "RULE-SET,ProxyGFWlist,节点选择"
  - "RULE-SET,ProxyGFW,节点选择"
  - "GEOSITE,YOUTUBE@CN,全球直连"
  - "GEOSITE,YOUTUBE,YouTube"
  - "GEOSITE,GOOGLE-PLAY@CN,全球直连"
  - "GEOSITE,GOOGLE,Google" 
  - "GEOSITE,CATEGORY-GAMES@CN,全球直连"
  - "GEOSITE,CATEGORY-GAMES,游戏平台"
  - "GEOSITE,CATEGORY-SCHOLAR-CN,全球直连"
  - "GEOSITE,TELEGRAM,Telegram"
  - "GEOSITE,CN,全球直连"
  - "GEOSITE,PRIVATE,全球直连"
  - "GEOIP,GOOGLE,Google,no-resolve"
  - "GEOIP,TELEGRAM,Telegram,no-resolve"
  - "GEOIP,CN,全球直连,no-resolve"
  - "GEOIP,LAN,全球直连,no-resolve"
  - "GEOIP,PRIVATE,全球直连,no-resolve"
  - "MATCH,漏网之鱼"