# 基本设置
port: 7890 # HTTP代理端口
socks-port: 7891 # SOCKS代理端口
#redir-port: 7892 # 透明代理端口，用于 Linux 和 MacOS
mixed-port: 7893 # HTTP(S) 和 SOCKS 代理混合端口
#tproxy-port: 7894
allow-lan: false # 允许局域网连接
bind-address: "*" # 绑定地址，* 表示所有地址
mode: rule # 代理模式，rule表示规则模式
log-level: info # 日志级别
ipv6: false
#  控制面板
# external-controller: 0.0.0.0:9093 # RESTful API 监听地址
# external-controller-tls: 0.0.0.0:9443 # RESTful API HTTPS 监听地址，需要配置 tls 部分配置文件
# secret: "123456"
# external-ui: ui
# external-ui-name: zashboard
# external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

unified-delay: true # 统一延迟
tcp-concurrent: true # TCP 并发

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
find-process-mode: always
global-client-fingerprint: chrome

#  TCP keep alive interval
#  这个选项大概用不到
# disable-keep-alive: false #目前在android端强制为true
# keep-alive-idle: 600
# keep-alive-interval: 15

profile:
  store-selected: true # 存储 select 选择记录
  store-fake-ip: true # 持久化 fake-ip

# 入站  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  mtu: 1500 # 最大传输单元,默认 9000
  auto-route: true
  auto-detect-interface: true

# 嗅探
sniffer:
  sniff:
    TLS:
      ports: [443, 8443]
      override-destination: true
    HTTP:
      ports: [80, 8080, 8880]
      override-destination: false
    QUIC:
      ports: [443, 8443]
      override-destination: true
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"

dns:
  enable: true
  ipv6: false
  prefer-h3: true
  enhanced-mode: redir-host
  cache-algorithm: arc
  use-system-hosts: true
  default-nameserver:
    - "119.29.29.29"
    - "223.5.5.5"
    - "114.114.114.114"
    - "tls://1.12.12.12:853"
    - "tls://223.5.5.5:853"
  nameserver:
    - "system"
    - "quic://223.5.5.5"
    - "tls://dot.pub:853"
    - "tls://dns.alidns.com"
  fallback:
    - "tls://1.1.1.1:853"
    - "https://dns.google/dns-query"
    - "tls://dns.google"
    - "tcp://208.67.222.222"
    - "tcp://8.26.56.2"
  proxy-server-nameserver:
    - "quic://223.5.5.5"
    - "tls://dot.pub"
    - "https://223.5.5.5/dns-query"

# geodata-mode: true/false
geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

proxy-groups:
  - name: 订阅信息
    icon: https://testingcf.jsdelivr.net/gh/aihdde/Rules@master/icon/Color/Yin_Yang.png
    type: select
    include-all: true
    filter: "Info-" # 这是一个独特的“接头暗号”
  - name: 节点选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - 自动选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
  - name: 手动切换
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 自动选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    include-all: true
    exclude-filter: (?i)家宽|家庭|商宽|落地
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 人工智能
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: Google
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: E-Hentai
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Ehentai.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 游戏平台
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 静态资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: select
    include-all: true
    proxies:
      - 日本负载-轮询
      - 美国负载-轮询
      - CF Workers
      - CF Workers-轮询
      - 节点选择
      - 自动选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 媒体CDN
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Filter.png
    type: select
    proxies:
      - 日本负载-轮询
      - 美国负载-轮询
      - CF Workers
      - CF Workers-轮询
      - 节点选择
      - 自动选择
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 全球直连
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 节点选择
  - name: 广告拦截
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - 全球直连
  - name: 漏网之鱼
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png
    type: select
    proxies:
      - 节点选择
      - 全球直连
  - name: 故障转移
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png
    type: fallback
    # lazy: false
    proxies:
      - 香港节点
      - 台湾节点
      - 日本节点
      - 美国节点
      - 手动切换
      - 全球直连
  - name: 香港节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)港|HK|hk|Hong Kong|HongKong|hongkong
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 台湾节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 日本节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 日本负载-轮询
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    type: load-balance
    strategy: round-robin  # <-- 核心策略：轮询
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: false
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan
    exclude-filter: (?i)家宽|家庭|商宽|落地
  - name: 美国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    exclude-filter: (?i)家宽|家庭|商宽|落地
    type: url-test
    interval: 300
    tolerance: 20
    # lazy: false
  - name: 美国负载-轮询
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    type: load-balance
    strategy: round-robin  # <-- 核心策略：轮询
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: false
    include-all: true
    filter: (?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
    exclude-filter: (?i)家宽|家庭|商宽|落地
  - name: CF Workers
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: false
    include-all: true
    filter: (?i)Cloudflare
    exclude-filter: (?i)家宽|家庭|商宽|落地
  - name: CF Workers-轮询
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: load-balance
    strategy: round-robin  # <-- 核心策略：轮询
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # lazy: false
    include-all: true
    filter: (?i)Cloudflare
    exclude-filter: (?i)家宽|家庭|商宽|落地
  - name: GLOBAL
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    type: select
    proxies:
      - 节点选择
      - 手动切换
      - 自动选择
      - 人工智能
      - Telegram
      - Google
      - YouTube
      - E-Hentai
      - 游戏平台
      - 静态资源
      - 媒体CDN
      - 全球直连
      - 广告拦截
      - 漏网之鱼
      - 故障转移
      - 香港节点
      - 台湾节点
      - 日本节点
      - 日本负载-轮询
      - 美国节点
      - 美国负载-轮询
      - CF Workers
      - CF Workers-轮询

rule-providers:
  ADBlock:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://adrules.top/adrules_domainset.txt
    path: ./ADBlock.txt
  cdn_domainset:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./sukkaw_ruleset/cdn_domainset.txt
  cdn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./sukkaw_ruleset/cdn_non_ip.txt
  EHentai:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/EHentai.list
    path: ./ruleset/EHentai.list
  AdditionalFilter:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/AdditionalFilter.list
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalFilter.list
  gfw:
    type: http
    behavior: domain
    format: text
    interval: 86400
    path: ./ruleset/gfw.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
  cmtyPROXYrules:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/cmtyPROXYrules.list
    url: https://raw.githubusercontent.com/cmyyx/backup/refs/heads/cmty-rules/cmtyPROXYrules.list
  cmtyDIRECTrules:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/cmtyDIRECTrules.list
    url: https://raw.githubusercontent.com/cmyyx/backup/refs/heads/cmty-rules/cmtyDIRECTrules.list
  cmtyPROXYmedia_cdn:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/cmtyPROXYmedia_cdn.list
    url: https://raw.githubusercontent.com/cmyyx/backup/refs/heads/cmty-rules/cmtyPROXYmedia_cdn.list
  cmtyJPrules:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/cmtyJPrules.list
    url: https://raw.githubusercontent.com/cmyyx/backup/refs/heads/cmty-rules/cmtyJPrules.list
  AWAvenue-Ads-Rule:
    type: http
    behavior: domain
    format: yaml
    path: ./ruleset/AWAvenue-Ads-Rule-Clash.yaml
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml
    interval: 86400
  SteamFix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/SteamFix.list
  ai_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 86400
    path: ./ruleset/ai_non_ip.txt
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt

rules:
  - "RULE-SET,cmtyPROXYrules,节点选择"
  - "RULE-SET,cmtyDIRECTrules,全球直连"
  - "RULE-SET,cmtyPROXYmedia_cdn,媒体CDN,no-resolve"
  - "RULE-SET,cmtyJPrules,日本节点"
  - "RULE-SET,ADBlock,广告拦截"
  - "RULE-SET,AdditionalFilter,广告拦截"
  - "RULE-SET,AWAvenue-Ads-Rule,广告拦截"
  - "RULE-SET,cdn_domainset,静态资源,no-resolve"
  - "RULE-SET,cdn_non_ip,静态资源,no-resolve"
  - "RULE-SET,EHentai,E-Hentai,no-resolve"
  - "RULE-SET,SteamFix,全球直连"
  - "RULE-SET,ai_non_ip,人工智能"
  - "RULE-SET,gfw,节点选择"
  - "GEOSITE,YOUTUBE@CN,全球直连"
  - "GEOSITE,YOUTUBE,YouTube"
  - "GEOSITE,GOOGLE-PLAY@CN,全球直连"
  - "GEOSITE,GOOGLE,Google" 
  - "GEOSITE,CATEGORY-GAMES@CN,全球直连"
  - "GEOSITE,CATEGORY-GAMES,游戏平台"
  - "GEOSITE,CATEGORY-SCHOLAR-CN,全球直连"
  - "GEOSITE,TELEGRAM,Telegram"
  # - "GEOSITE,proxy,节点选择"
  # - "GEOSITE,gfw,节点选择"
  - "GEOSITE,CN,全球直连"
  - "GEOSITE,PRIVATE,全球直连"
  - "GEOIP,GOOGLE,Google,no-resolve"
  - "GEOIP,TELEGRAM,Telegram,no-resolve"
  - "GEOIP,CN,全球直连,no-resolve"
  - "GEOIP,LAN,全球直连,no-resolve"
  - "GEOIP,PRIVATE,全球直连,no-resolve"
  - "MATCH,漏网之鱼"